### ISSUE TITLE
how to uninstall?:)

### ISSUE THREAD

**Issue by KvizadSaderah** [Neutrollized/dynmotd#1]
i delete file `/usr/local/bin/dynmotd`, and now got 
`-bash: /usr/local/bin/dynmotd: No such file or directory`
how to fix it?

**Comment by Neutrollized** [comment]
Sorry -- I just saw this. 

You will have to delete `/etc/profile.d/dynmotd.sh` as well.

**Comment by rtulke** [comment]
in newer versions dynmotd has an uninstall option try --uninstall

latest version on https://github.com/rtulke/dynmotd
